AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  InstanceType:
    Description: "EC2 instance type"
    Type: String
    Default: "t2.micro"

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: "testKey1120"
      ImageId: "testId"
      Number :"1"
      Number2:"01"
      Number3:"001"
      SecurityGroups:
        - !Ref InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH access"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "192.168.1.0/27"

Outputs:
  InstanceId:
    Description: "InstanceId of the newly created EC2 instance"
    Value: !Ref MyEC2Instance
  PublicIP:
    Description: "Public IP address of the newly created EC2 instance"
    Value: !GetAtt 
      - MyEC2Instance
      - PublicIp
