AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  InstanceType:
    Description: "EC2 instance type"
    Type: String
    Default: "{{instance_type}}"

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: "{{key_name}}"
      ImageId: "{{key_name}}"
      SecurityGroups:
        - !Ref InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable SSH access"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "{{cidr_ip}}"

Outputs:
  InstanceId:
    Description: "InstanceId of the newly created EC2 instance"
    Value: !Ref MyEC2Instance
  PublicIP:
    Description: "Public IP address of the newly created EC2 instance"
    Value: !GetAtt 
      - MyEC2Instance
      - PublicIp
